### ISSUE TITLE
Nested configurations support

### ISSUE THREAD

**Issue by kmahar** [vknabel/vscode-swiftlint#23]
Hello! 

SwiftLint supports [nested configurations](https://github.com/realm/SwiftLint#nested-configurations), for example you can have a top-level configuration in your root directory but define a different set of rules for use in a sub-directory. 

As far as I can tell, this extension does not support nested configurations. A rule I have disabled in a sub-directory (but enabled in a top-level directory) incorrectly shows up in as a violation for files in the subdirectory.

It would be really nice to have support for this in the extension as right now I just have to ignore a bunch of violations in a directory.
However, I'm not exactly sure how one would add it, because as the linked README section notes it does not work when using the `--config` parameter which it [looks like](https://github.com/vknabel/vscode-swiftlint/blob/17c755ea3722591b0972b961ecde52a707e3d8bd/src/SwiftLintConfig.ts#L43) you use.

**Comment by vknabel** [comment]
Hey @kmahar!

Yes currently this extension does not support nested configurations and I wasn't aware of it. But I definitely plan to do so.
In https://github.com/vknabel/vscode-swiftlint/issues/24 there was an extension bug caused due to wrong paths passed to SwiftLint.

Especially thanks for pointing out that the use of `--config` breaks nested configurations. This helps a lot.

**Comment by kmahar** [comment]
@vknabel Awesome, thank you for getting back to me!

**Comment by vknabel** [comment]
Hi @kmahar.

It's been a while, but there are news:
The freshly released [1.4.0](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.4.0) now supports nested configs _if `swiftlint.configSearchPaths` is `[]` (new default)_.
