### ISSUE TITLE
SwiftLint process doesn't terminate and consumes a lot of memory

### ISSUE THREAD

**Issue by MaxDesiatov** [vknabel/vscode-swiftlint#24]
As reported in https://github.com/realm/SwiftLint/issues/3461, when using this extension with certain projects, it launches `swiftlint` processes in a way that don't terminate and consume a lot of memory. Here I attach a few screenshots from Activity Monitor that show that these processes consume tens of gigabytes of RAM and stay running for minutes. They also don't terminate after I close VSCode, and keep running, consuming 10-20% CPU load on average.

<img width="411" alt="Screenshot 2020-12-09 at 21 56 37" src="https://user-images.githubusercontent.com/112310/101694597-434d8e80-3a6b-11eb-8d4c-bb2355eea3e9.png">
<img width="589" alt="Screenshot 2020-12-09 at 21 34 29" src="https://user-images.githubusercontent.com/112310/101694603-46487f00-3a6b-11eb-8279-bb3cbdb06f36.png">

**Comment by vknabel** [comment]
@MaxDesiatov thanks a lot for your report. It seems the latest 1.2.5 release is broken. So I re-released 1.2.4 as 1.2.6.
Tomorrow evening I will have a deeper look on this!

**Comment by MaxDesiatov** [comment]
Awesome, thanks!

**Comment by vknabel** [comment]
I didn't have enough time to create and actually test a proper fix, but there is a first candidate.
It tries to fix the bug itself and to terminate stale SwiftLint instances. 

If you want to give it a try, I tagged [1.2.7-beta.0](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.2.7-beta.0) and uploaded the extension for manual installation. It will probably take until the weekend or even early next week until the official release due to lack of time to test multiple use cases.

**Comment by MaxDesiatov** [comment]
No problem at all, thanks for your hard work!

**Comment by vknabel** [comment]
The fix has now been released as 1.2.7

**Comment by MaxDesiatov** [comment]
Great stuff, thank you 👍

**Comment by vknabel** [comment]
You did a great report, too!
